name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 15.x
        cache: 'npm'

    - run: npm install

    - run: npm run build

    - uses: oleksiyrudenko/gha-git-credentials@v2-latest
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'

    - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: npm run deploy-gh-pages-ci
